apiVersion: apps/v1
kind: Deployment
metadata:
  name: ionic-deployment-vehicle
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ionic-vehicle
  template:
    metadata:
      labels:
        app: ionic-vehicle
    spec:
      containers:
      - name: ionic-vehicle
        image: ghcr.io/ionicerp/vehicle_fe_angular:latest
        # imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: API_URL
          value: "https://app.ionicerp.com"
        - name: ENVIRONMENT_NAME
          value: "production"
      imagePullSecrets:
      - name: my-github-secret
      # - name: my-regcred
---
apiVersion: v1
kind: Service
metadata:
  name: ionic-service-vehicle
spec:
  selector:
    app: ionic-vehicle
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  # type: LoadBalancer
