name: Create and publish a Docker image and trigger Pod update

on:
  push:
    branches: main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.MY_GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
              docker build . --tag ghcr.io/ionicerp/vehicle_fe_angular:latest
              docker push ghcr.io/ionicerp/vehicle_fe_angular:latest

      - name: Set up kubeconfig
        run: echo "${{ secrets.KUBECONFIG }}" | base64 -d > kubeconfig

      - name: Deploy to Kubernetes
        run: |
          export KUBECONFIG=kubeconfig
          kubectl rollout restart deployment/ionic-deployment-vehicle
  



  # deploy:
  #   needs: build-and-push-image
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v3

  #   - name: Set up kubeconfig
  #     run: echo "${{ secrets.KUBECONFIG }}" | base64 -d > kubeconfig

  #   # - name: Create Docker registry secret
  #   #   run: |
  #   #     export KUBECONFIG=kubeconfig
  #   #     kubectl create secret docker-registry my-github-secret --docker-server=ghcr.io --docker-username=${{ secrets.MY_GITHUB_USERNAME }} --docker-password=${{ secrets.MY_GITHUB_TOKEN }} || true

  #   - name: Deploy to Kubernetes
  #     run: |
  #       export KUBECONFIG=kubeconfig
  #       kubectl apply -f Deployment.yaml  # replace with your deployment file path
